name: Check

on:
  pull_request:

jobs:
  lint_format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Lint code
        run: poetry run ruff check .

      - name: Check formatting
        run: |
          poetry run black --check .
          poetry run isort --check-only .

  test:
    runs-on: ubuntu-latest
    needs: lint_format
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest

  type_check:
    runs-on: ubuntu-latest
    needs: lint_format
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Type check
        run: poetry run pyright

  security_check:
    runs-on: ubuntu-latest
    needs: lint_format
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Security check
        run: poetry run bandit -c bandit.yaml .
